Addy/urls.py
# from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('stars/', include('stars.urls')),
]

stars/urls.py
from django.urls import path
from . import views

app_name = 'stars'
urlpatterns = [
    path('', views.index, name='index'),
    path('list/', views.list, name='list'),
    path('add/', views.create, name='create'),

]

stars/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=70)
    email = models.EmailField()

    def __str__(self):
        return '%s %s' % (self.name, self.email)

stars/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse

from stars.ContactForm import ContactForm
from stars.models import Contact


def index(request):

    return render(request, 'stars/index.html')

def list(request):

    contact_list = Contact.objects.all()

    context = {'contacts': contact_list}

    return render(request, 'stars/list.html', context)


def create(request):

    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            h = Contact()
            h.name = data['name']
            h.email = data['email']
            h.save()

        return HttpResponseRedirect(reverse('stars:list'))


    else:
        form = ContactForm()
    return render(request, 'stars/create.html', {'form': form})

stars/templates/backup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
{% comment %} <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">{% endcomment %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body >
<nav class="navbar  sticky-top navbar-dark bg-dark">
 <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
</nav>
{% block content %}
{% endblock %}
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</body>
</html>

stars/templates/stars/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">


      {% block title %}
         <title></title>
    {% endblock %}

  </head>
  <body>
<nav style="background-color: #e3f2fd;" class="navbar navbar-expand-lg  navbar-light">
  <a class="navbar-brand" href="#">Addy</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse float-left" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

     {% block navigation %}
          <li class="nav-item active">
        <a class="nav-link" href="{%  url 'stars:index'  %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%  url 'stars:list'  %}">View All Contacts</a>
      </li>
        <li class="nav-item">
        <a class="nav-link btn btn-default" href="{%  url 'stars:create'  %}">
              <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Add</button>
        </a>

      </li>

    {% endblock %}

    </ul>

  </div>
</nav>
    <div class="container">

      {% block content %}
           <h1>Hello, world!</h1>
        {% endblock %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

stars/templates/stars/create.html
{% extends 'stars/base.html' %}

{% block title %}
    <title>Create</title>
{% endblock %}

{% block content %}

    <div style="margin: 2em" class="card">

  <div class="card-body">
    <h5 class="card-title">Add Contact</h5>
     <form method="POST">{% csrf_token %}
  <div class="form-group">

        <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
            <br />
        <input type="submit" class="btn btn-primary" value="Add" />
    </form>
  </div>

</form>

  </div>
</div>
{% endblock %}

stars/templates/stars/index.html
{% extends 'stars/base.html' %}

{% block title %}
    <title>Addy - Welcome</title>
{% endblock %}



{% block content %}


    <div style="margin: 2em" class="alert alert-warning alert-dismissible fade show" role="alert">
          <strong>You're here nice !!</strong> You can Create an email list with this simple python app
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
     </div>


    <div class="card text-center">
          <div class="card-header">
            Meet Addy !!
          </div>
          <div class="card-body">
            <h5 class="card-title">Addy is an application which stores names and email addresses in an SQLite  database:</h5>

            <a href="{%  url 'stars:list'  %}" class="btn btn-primary">View all Contacts</a>
               <a href="{%  url 'stars:create'  %}" class="btn btn-primary">Add Record</a>
          </div>
          <div class="card-footer text-muted">
           Writing with Python -Django
          </div>
</div>

{% endblock %}

stars/templates/stars/list.html
{% extends 'stars/base.html' %}

{% block title %}
    <title>Addy - List</title>
{% endblock %}

{% block content %}



    <table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
  {% if contacts %}
  {% for contact in contacts %}
    <tr>
      <th scope="row">{{ forloop.counter }}</th>
      <td>{{ contact.name }}</td>
      <td>{{ contact.email }}</td>
    </tr>
  {% endfor %}
  {% endif %}
  </tbody>
</table>
{% endblock %}